### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by ORCA666** [hasherezade/antianalysis_demos#2]
hey, hope your good...
i was trying to build [neutrino_checks](https://github.com/hasherezade/antianalysis_demos/blob/master/neutrino_checks.cpp) using visual studio 2019. 
and i had some building errors, i tried some types casting and some tricks but it is not working as it should :p 

here's a screenshot:

![Screenshot 2021-06-26 125647](https://user-images.githubusercontent.com/66519611/123509572-ec15b100-d67e-11eb-9f8e-f6b6e08388fe.png)

and then i saw [issues#1](https://github.com/hasherezade/antianalysis_demos/issues/1) and i wont mind knowing the names too :>

anyways thanks for your time, and your code,  and have a nice day !

hope you reply soon

**Comment by hasherezade** [comment]
ok, it seems that you have UNICODE APIs enabled in your project. try to disable them and it should be fine.
also, I highly recommend you to generate the full project via CMake in order to have it with all required environment variables set.
